// action types

export const SHOW_SIDEDRAWER = 'SHOW_SIDEDRAWER'
export const HIDE_SIDEDRAWER = 'HIDE_SIDEDRAWER'
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SET_USER = 'SET_USER'

export const SET_USER_PHOTOS = 'SET_USER_PHOTOS'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'

export const UPDATE_PROFILE_BASICS_START = 'UPDATE_PROFILE_BASICS_START'
export const UPDATE_PROFILE_BASICS_SUCCESS = 'UPDATE_PROFILE_BASICS_SUCCESS'
export const UPDATE_PROFILE_BASICS_ERROR = 'UPDATE_PROFILE_BASICS_ERROR'

export const UPDATE_PROFILE_ABOUT_START = 'UPDATE_PROFILE_ABOUT_START'
export const UPDATE_PROFILE_ABOUT_SUCCESS = 'UPDATE_PROFILE_ABOUT_SUCCESS'
export const UPDATE_PROFILE_ABOUT_ERROR = 'UPDATE_PROFILE_ABOUT_ERROR'

export const ADD_PROFILE_PHOTO_START = 'ADD_PROFILE_PHOTO_START'
export const ADD_PROFILE_PHOTO_SUCCESS = 'ADD_PROFILE_PHOTO_SUCCESS'
export const ADD_PROFILE_PHOTO_ERROR = 'ADD_PROFILE_PHOTO_ERROR'

export const DELETE_PHOTO_START = 'DELETE_PHOTO_START'
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS'
export const DELETE_PHOTO_ERROR = 'DELETE_PHOTO_ERROR'

export const SET_MAIN_PHOTO_START = 'SET_MAIN_PHOTO_START'
export const SET_MAIN_PHOTO_SUCCESS = 'SET_MAIN_PHOTO_SUCCESS'
export const SET_MAIN_PHOTO_ERROR = 'SET_MAIN_PHOTO_ERROR'

export const FETCH_PROFILE_PHOTOS_START = 'FETCH_PROFILE_PHOTOS_START'
export const FETCH_PROFILE_PHOTOS_SUCCESS = 'FETCH_PROFILE_PHOTOS_SUCCESS'
export const FETCH_PROFILE_PHOTOS_ERROR = 'FETCH_PROFILE_PHOTOS_ERROR'

export const CREATE_MEETING_START = 'CREATE_MEETING_START'
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
export const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR'

export const EDIT_MEETING_START = 'EDIT_MEETING_START'
export const EDIT_MEETING_SUCCESS = 'EDIT_MEETING_SUCCESS'
export const EDIT_MEETING_ERROR = 'EDIT_MEETING_ERROR'

export const FETCH_DASHBOARD_MEETINGS_START = 'FETCH_DASHBOARD_MEETINGS_START'
export const FETCH_DASHBOARD_MEETINGS_SUCCESS = 'FETCH_DASHBOARD_MEETINGS_SUCCESS'
export const FETCH_DASHBOARD_MEETINGS_ERROR = 'FETCH_DASHBOARD_MEETINGS_ERROR'

export const RESET_DASHBOARD_STATE = 'RESET_DASHBOARD_STATE'

export const FETCH_PROFILE_MEETINGS_START = 'FETCH_PROFILE_MEETINGS_START'
export const FETCH_PROFILE_MEETINGS_SUCCESS = 'FETCH_PROFILE_MEETINGS_SUCCESS'
export const FETCH_PROFILE_MEETINGS_ERROR = 'FETCH_PROFILE_MEETINGS_ERROR'

export const FETCH_SELECTED_MEETING_START = 'FETCH_SELECTED_MEETING_START'
export const FETCH_SELECTED_MEETING_SUCCESS = 'FETCH_SELECTED_MEETING_SUCCESS'
export const FETCH_SELECTED_MEETING_ERROR = 'FETCH_SELECTED_MEETING_ERROR'

export const JOIN_MEETING_START = 'JOIN_MEETING_START'
export const JOIN_MEETING_SUCCESS = 'JOIN_MEETING_SUCCESS'
export const JOIN_MEETING_ERROR = 'JOIN_MEETING_ERROR'

export const LEAVE_MEETING_START = 'LEAVE_MEETING_START'
export const LEAVE_MEETING_SUCCESS = 'LEAVE_MEETING_SUCCESS'
export const LEAVE_MEETING_ERROR = 'LEAVE_MEETING_ERROR'

export const CANCEL_MEETING_TOGGLE_START = 'CANCEL_MEETING_TOGGLE_START'
export const CANCEL_MEETING_TOGGLE_SUCCESS = 'CANCEL_MEETING_TOGGLE_SUCCESS'
export const CANCEL_MEETING_TOGGLE_ERROR = 'CANCEL_MEETING_TOGGLE_ERROR'

export const ADD_MEETING_COMMENT_START = 'ADD_MEETING_COMMENT_START'
export const ADD_MEETING_COMMENT_SUCCESS = 'ADD_MEETING_COMMENT_SUCCESS'
export const ADD_MEETING_COMMENT_ERROR = 'ADD_MEETING_COMMENT_ERROR'

export const ACTIVITY_LISTENER_CALLBACK_START = 'ACTIVITY_LISTENER_CALLBACK_START'
export const ACTIVITY_LISTENER_CALLBACK_SUCCESS = 'ACTIVITY_LISTENER_CALLBACK_SUCCESS'
export const ACTIVITY_LISTENER_CALLBACK_ERROR = 'ACTIVITY_LISTENER_CALLBACK_ERROR'

export const FETCH_SOMEONE_ELSE_PROFILE_START = 'FETCH_SOMEONE_ELSE_PROFILE_START'
export const FETCH_SOMEONE_ELSE_PROFILE_SUCCESS = 'FETCH_SOMEONE_ELSE_PROFILE_SUCCESS'
export const FETCH_SOMEONE_ELSE_PROFILE_ERROR = 'FETCH_SOMEONE_ELSE_PROFILE_ERROR'
