// action types

export const SHOW_SIDEDRAWER = 'SHOW_SIDEDRAWER'
export const HIDE_SIDEDRAWER = 'HIDE_SIDEDRAWER'
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
