// action types

export const SHOW_SIDEDRAWER = 'SHOW_SIDEDRAWER'
export const HIDE_SIDEDRAWER = 'HIDE_SIDEDRAWER'
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SET_USER = 'SET_USER'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const CREATE_MEETING_START = 'CREATE_MEETING_START'
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
export const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR'

export const EDIT_MEETING_START = 'EDIT_MEETING_START'
export const EDIT_MEETING_SUCCESS = 'EDIT_MEETING_SUCCESS'
export const EDIT_MEETING_ERROR = 'EDIT_MEETING_ERROR'

export const FETCH_DASHBOARD_MEETINGS_START = 'FETCH_DASHBOARD_MEETINGS_START'
export const FETCH_DASHBOARD_MEETINGS_SUCCESS = 'FETCH_DASHBOARD_MEETINGS_SUCCESS'
export const FETCH_DASHBOARD_MEETINGS_ERROR = 'FETCH_DASHBOARD_MEETINGS_ERROR'

export const RESET_DASHBOARD_STATE = 'RESET_DASHBOARD_STATE'

export const FETCH_SELECTED_MEETING_START = 'FETCH_SELECTED_MEETING_START'
export const FETCH_SELECTED_MEETING_SUCCESS = 'FETCH_SELECTED_MEETING_SUCCESS'
export const FETCH_SELECTED_MEETING_ERROR = 'FETCH_SELECTED_MEETING_ERROR'

export const RESET_SELECTED_MEETING = 'RESET_SELECTED_MEETING'
